blank_issues_enabled: false
contact_links:
  - name: Read the API documentation
    url: https://myparcelnl.github.io/api/
    about: The API documentation contains in-depth information on all our public endpoints.
  - name: Contact customer support
    url: https://www.myparcel.nl/services/contact/
    about: For issues regarding your account and shipments.
