name: '🔸 Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: myparcelnl/actions/yarn-install@v3
        with:
          node-version: 18

      - name: 'Run tests'
        run: yarn test:run --coverage

      - uses: codecov/codecov-action@v3
        with:
          files: coverage/clover.xml

      - uses: codacy/codacy-coverage-reporter-action@v1
        with:
          coverage-reports: coverage/clover.xml
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
