name: '🔸 Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: 'Handle coverage cache'
        uses: actions/cache@v3
        id: coverage-cache
        with:
          path: coverage
          key: coverage-${{ hashFiles('yarn.lock', 'src/**/*', 'test/**/*') }}

      - uses: myparcelnl/actions/yarn-install@v3
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          node-version: 18

      - name: 'Run tests'
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        #language=sh
        run: | 
          yarn test:coverage

      - uses: codecov/codecov-action@v3
        with:
          files: coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: codacy/codacy-coverage-reporter-action@v1
        with:
          coverage-reports: coverage/clover.xml
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
