name: 'Publish new release 🚀'

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/--test.yml
    secrets: inherit

  release:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GH_REPO_TOKEN }}

      # TODO: Switch to v3 with app credentials when GitHub apps are allowed to bypass status checks. https://github.com/orgs/community/discussions/43460
      - uses: myparcelnl/actions/setup-git-credentials@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: myparcelnl/actions/yarn-install@v3
        with:
          node-version: 18

      - uses: ./.github/actions/build

      - uses: myparcelnl/actions/semantic-release@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  rebase-prs:
    needs: release
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: peter-evans/rebase@v2
        with:
          token: ${{ steps.credentials.outputs.token }}
          base: ${{ github.ref_name }}
          exclude-drafts: true
          exclude-labels: 'dependencies'
