name: 'Publish new release 🚀'

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: myparcelnl/js-sdk/.github/workflows/test.yml@main

  release:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: myparcelnl/actions/yarn-install@v2

      - run: yarn run build

      - uses: myparcelnl/actions/semantic-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
