name: 'Publish new release 🚀'

on:
  push:
    branches:
      - main
    paths-ignore:
      - ./**/*.md
      - .eslintrc
      - .gitignore

  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or commit to run tests on'
        required: true
        type: string

  repository_dispatch:
    types: [ test-command ]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: 'Run tests '
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.event.client_payload.pull_request.head.label || '' }}
          persist-credentials: false

      - uses: myparcelnl/actions/yarn-install@v1

      - name: 'Run tests'
        run: yarn run test:coverage

      - name: Update code coverage
        uses: codecov/codecov-action@v2

      - name: 'Trigger release'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          event-type: release
