name: 'Run tests 🧪'

on:
  workflow_call:

  push:
    branches:
      - main
    paths-ignore:
      - ./**/*.md
      - ./.github/**/*
      - .eslintrc
      - .gitignore

  pull_request: ~

  workflow_dispatch: ~

  repository_dispatch:
    types: [ test-command ]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: 'Run tests'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.label || '' }}
          persist-credentials: false

      - uses: myparcelnl/actions/yarn-install@v1

      - name: 'Run tests'
        run: yarn run test:coverage

      - name: Update code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
